input SignupInput {
	username: String!
	email: String!
	password: String!
}

scalar token

type UserInfo {
	jwt: String!
}


type Query {
	login(email: String!, password: String!): UserInfo
}

type Mutation {
	signup(signupInput: SignupInput!): UserInfo
}